export interface CompanyData {
    companyName: string,
    address: string,
    registrationDate: Date,
    numberOfEmployees: number,
    raisedCapital: number,
    turnover: number,
    netProfite: number,
    contactNumber: string,
    contactEmail: string,
    companyWebsite: string,
    loanAmount: number,
    loanInterest: number,
    accountStatus: boolean,
}